---
version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:latest

    steps:
    - checkout
    - setup_remote_docker
    - run: docker info
    - run: uname -a
      # Register binfmt_misc targets for cross-building
    - run: docker run --privileged linuxkit/binfmt:v0.6
    - run: make
    - run: docker images

  build_master:
    docker:
    - image: circleci/golang:latest

    steps:
    - checkout
    - setup_remote_docker
    - run: docker info
    - run: docker run --privileged linuxkit/binfmt:v0.6
    - run: make SUFFIX=
    - run: docker images
    - run: make tag SUFFIX=
    - run: docker login -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
    - run: make push

workflows:
  version: 2
  prometheus:
    jobs:
    - build:
        filters:
          branches:
            ignore: master
    - build_master:
        filters:
          branches:
            only: master
